### ISSUE TITLE
error reading Seurat object

### ISSUE THREAD

**Issue by nbahlis** [BaderLab/scClustViz#25]
Hello 

I am getting the following error when running readFromSeurat:

Error in readFromSeurat(immune.combined) : 
  trying to get slot "cell.embeddings" from an object of a basic class ("NULL") with no slots

This seurat object was generated using canonical correlation analysis RunCCA

thanks

**Comment by innesbre** [comment]
Right now the default readFromSeurat function expects you to have followed the workflow in the Seurat tutorial and looks for PCA and tSNE results from those slot locations in the Seurat object. Since you’ve done something more interesting you’re going to have to use the (poorly named) readFromManual function to specifically indicate where scClustViz should look for the dimensionality reduction embeddings used for the clustering (ie CCA embeddings) and the 2D coordinates for visualization. Let me know if that works!

www.baderlab.org/BrendanInnes<http://www.baderlab.org/BrendanInnes>

On Nov 12, 2018, at 14:22, nbahlis <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello

I am getting the following error when running readFromSeurat:

Error in readFromSeurat(immune.combined) :
trying to get slot "cell.embeddings" from an object of a basic class ("NULL") with no slots

This seurat object was generated using canonical correlation analysis RunCCA

thanks
