### ISSUE TITLE
Parameters for sctransform based data

### ISSUE THREAD

**Issue by knokknok** [BaderLab/scClustViz#34]
Would you have suggestions for how to best parametrize when using the Seurat/sctransform workflow?
Thanks!

**Comment by innesbre** [comment]
If you're using the log-normalized counts from the 'data' slot of the "SCT" assay (see https://satijalab.org/seurat/v3.0/sctransform_vignette.html), you can use the same parameters as always with Seurat (pseudocount=1,exponent=exp(1)), since they use R's log1p function to add a pseudocount of 1 and transform everything to natural log space.
