### ISSUE TITLE
Error in validObject(.Object) while running CalcAllSCV

### ISSUE THREAD

**Issue by KabitaBaral1** [BaderLab/scClustViz#40]
Hi,
I am trying to run scClustViz. I have an object with my normalized, dimension reduced and clustered dataset (using Seurat). I first used function grep and then getMD and that gave me metadata with very low (0-3) values for nCount_RNA and nFeature_RNA. I am not sure if this is expected and has nothing to do with my error. 
Then, when I try to use function "CalcAllSCV", I get the following error:
"--------------------------------------
--------------------------------------
Processing cluster solution: orig.ident
--------------------------------------
-- Calculating cluster-wise gene statistics --
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=53s  
-- Calculating differential expression cluster vs rest effect size --
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=11s  
-- Testing differential expression cluster vs rest --
-- Testing differential expression between clusters --
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=09s  
 
--------------------------------------
--------------------------------------
Processing cluster solution: nCount_RNA
--------------------------------------
Error in validObject(.Object) : 
  invalid class “sCVdata” object: invalid object for slot "Clusters" in class "sCVdata": got class "numeric", should be or extend class "factor""

Thank you

**Comment by innesbre** [comment]
By "function grep" do you mean this command:
```
your_cluster columns <- grepl("res[.0-9]+$",
                              names(getMD(your_scRNAseq_data_object)))
```
That command is an example of how you might pull your cluster columns out of your metadata dataframe.  The `CalcAllSCV(...,clusterDF= )` argument expects a dataframe where each column is a character vector or factor with cluster assignments.  Check to see if that's what the grep function is getting you. It looks like that's not what its getting, since you've given it columns with titles like "orig.ident" and "nCount_RNA", which are not the cluster results in usual Seurat metadata.
