### ISSUE TITLE
unable to find an inherited method for function ‘getMD’ for signature ‘"data.frame

### ISSUE THREAD

**Issue by RoanZaied** [BaderLab/scClustViz#43]
Hey! I am trying to implement the basic usage but when I run :
**your_cluster_columns <- grepl("res[.0-9]+$",
                              names(getMD(pbmc2k@meta.data)))
)**

I get the following error:
**Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘getMD’ for signature ‘"data.frame"’**

I am unsure what the correct input object format is. 

My meta.data df has the following columns:

cell.id|orig.ident | nCount_RNA | nFeature_RNA | percent.mt | RNA_snn_res.0.35 | seurat_clusters | 

Thank you for your time.

**Comment by innesbre** [comment]
getMD is a accessor function that extracts the metadata from your Seurat or SingleCellExperiment object. So you don't need to specify pbmc2k@meta.data, you can just use getMD(pbmc2k). Or skip the getMD function and just use pbmc2k@meta.data. They should return the same thing.
The goal of this line of the demo code is just to programmatically grab the clustering results from your Seurat metadata. You could just provide a dataframe of cluster results to CalcAllSCV yourself. I think Seurat has changed how they store cluster results in the metadata, so that grep function might not find the things it's looking for anyway.

On Jun. 14, 2020 10:45 a.m., RoanZaied <notifications@github.com> wrote:

Hey! I am trying to implement the basic usage but when I run :
your_cluster_columns <- grepl("res[.0-9]+$",
names(getMD(pbmc2k@meta.data<mailto:pbmc2k@meta.data>)))
)

I get the following error:
Error in (function (classes, fdef, mtable) :
unable to find an inherited method for function ‘getMD’ for signature ‘"data.frame"’

I am unsure what the correct input object format is.

My meta.data df has the following columns:

cell.id|orig.ident | nCount_RNA | nFeature_RNA | percent.mt | RNA_snn_res.0.35 | seurat_clusters |

Thank you for your time.

**Comment by RoanZaied** [comment]
Thank you very much!
